import { TextStyle, ViewStyle, ImageStyle } from "react-native";
export declare const GRID_ITEM_TOTAL_WIDTH = 46;
export declare const TOTAL_OVERLAY_PADDING = 60;
export declare const TOTAL_NON_OVERLAY_PADDING = 32;
export declare const SCREEN_HEIGHT: number;
export declare const SCREEN_WIDTH: number;
export declare const RATIO: number;
export declare const FULL: ViewStyle;
export declare const PADDING_TOP_EIGHT: ViewStyle;
export declare const PADDING_TOP_ZERO: ViewStyle;
export declare const MARGIN_BOTTOM_EIGHT: ViewStyle;
export declare const MARGIN_BOTTOM_ZERO: ViewStyle;
export declare const ALIGN_BASELINE: ViewStyle;
export declare const SINGLE_IMAGE_STYLE: ImageStyle;
export declare const IMAGE_FLATLIST_STYLE: ViewStyle;
export declare const SLIDESHOW_CONTAINER: ViewStyle;
export declare const FLATLIST_ITEM_STYLE: ImageStyle;
export declare const OVERLAY_IMAGE_CAPTION_CONTAINER: ViewStyle;
export declare const CAPTION_FILLER_VIEW: ViewStyle;
export declare const IMAGE_CAPTION_CONTAINER: ViewStyle;
export declare const IMAGE_CAPTION: TextStyle;
export declare const IMAGE_CAPTION_SCROLLVIEW: ViewStyle;
export declare const READ_MORE_CONTAINER: ViewStyle;
export declare const SHOW_LESS_CONTAINER: ViewStyle;
export declare const READ_MORE_TEXT: TextStyle;
export declare const SEPARATOR_WITH_READMORE: ViewStyle;
export declare const SEPARATOR: ViewStyle;
export declare const OVERLAY_GRID_SCROLLVIEW: ViewStyle;
export declare const OVERLAY_GRID_CONTAINER: ViewStyle;
export declare const GRID_CONTAINER: ViewStyle;
export declare const THUMBNAIL_GRID: ViewStyle;
export declare const IMAGE_GRID_ITEM: ImageStyle;
export declare const CURRENT_IMAGE_GRID_ITEM: ImageStyle;
export declare const MORE_PHOTOS: ViewStyle;
export declare const MORE_PHOTOS_TEXT: TextStyle;
export declare const CHEVRON: ImageStyle;
export declare const MASKING: ViewStyle;
export declare const BUTTON_CONTAINER_STYLE: ViewStyle;
export declare const BUTTON_STYLE: ViewStyle;
export declare const BUTTON_TEXT_STYLE: TextStyle;
export declare const OVERLAY_CONTENT_CONTAINER: ViewStyle;
